# Generated by Django 4.2.4 on 2023-08-13 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbapp', '0002_rename_text_message_body_message_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
